HTML processing
thunder/paragraphs_paste pull request #24
Opened 2020-04-16 13:11 UTC by ol0lll

2020-04-20 12:01 UTC, chrfritsch commented
With Firefox latest, I have to press Ctrl-V two times to trigger the paste event.

2020-04-21 14:40 UTC, chrfritsch commented
Pasting two times a different text, creates two paragraphs with the same text

2020-04-21 15:18 UTC, chrfritsch commented
With split method "oEmbed" enabled, I get some empty paragraphs by pasting something like

```
essen. Hunger kennen die meisten Menschen in Deutschland nicht mehr.

https://www.youtube.com/watch?v=4ksufBoeZm8

Das hat sich auch auf unsere Körper ausgewirkt: Laut der Ernährungsmedizinerin Dr. Petra

2020-04-21 15:43 UTC, chrfritsch requested changes

2020-04-21 15:43 UTC, chrfritsch commented on js/paragraphs-paste.js
> +    editableElem.innerHTML = '';
Looks like this is not needed

2020-04-22 07:07 UTC, ol0lll commented on js/paragraphs-paste.js
> +    editableElem.innerHTML = '';
I think we need that, when I paste a second time I get the content from before additionally to what I actually pasted

2020-04-22 07:08 UTC, ol0lll commented on js/paragraphs-paste.js
> +    editableElem.innerHTML = '';
Also if someone was to type in the editor while in focus it would be better to clear it.

2020-04-22 07:08 UTC, chrfritsch commented on js/paragraphs-paste.js
> +    editableElem.innerHTML = '';
With the form reset I did?

2020-04-22 08:54 UTC, chrfritsch approved these changes

2020-04-22 08:55 UTC, ol0lll commented
Created follow-up for 
* Additional empty paragraphs created
https://www.drupal.org/project/paragraphs_paste/issues/3129870
* Format content according to target field type
https://www.drupal.org/project/paragraphs_paste/issues/3129875

2020-04-22 08:58 UTC, merged